<a href="https://colab.research.google.com/github/gosmdochi/linear-algebra/blob/main/%EC%8B%A4%EC%8A%B5zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World!")

Hello World!


In [ ]:
print("배고파 죽을수도 있을 것 같아")

배고파 죽을수도 있을 것 같아


---
# 1. 파이썬 기초
---

### 프린트

In [ ]:
print("Hello, world")

# integer
x = 3
print("정수: %01d, %02d, %03d, %04d, %05d" % (x, x, x, x, x))

# float
x = 256.123
print("정수: %01f, %02f, %03f" % (x, x, x))

# string
x = "Hello world"
print("문자역: [%s]" % (x))

Hello, world
정수: 3, 03, 003, 0003, 00003
정수: 256.123000, 256.123000, 256.123000
문자역: [Hello world]


### 반복문, 조건문

In [ ]:
contents = ["Regression", "Classification", "SYM", "Clustering", "Dimension reduction",
            "NN", "CNN", "AE", "GAN", "RNN"]

for con in contents:
  if con in ["Regression", "Classification", "SYM", "Clustering", "Dimension reduction"]:
    print("%s은(는) 기계학습 내용입니다." %con)
  elif con in ["CNN"]:
    print("%s은(는) convolutional neural network 내용입니다." %con)
  else:
    print("%s은(는) 심층학습 내용입니다." %con)

Regression은(는) 기계학습 내용입니다.
Classification은(는) 기계학습 내용입니다.
SYM은(는) 기계학습 내용입니다.
Clustering은(는) 기계학습 내용입니다.
Dimension reduction은(는) 기계학습 내용입니다.
NN은(는) 심층학습 내용입니다.
CNN은(는) convolutional neural network 내용입니다.
AE은(는) 심층학습 내용입니다.
GAN은(는) 심층학습 내용입니다.
RNN은(는) 심층학습 내용입니다.


### 반복문과 인덱스

In [ ]:
for (i, con) in enumerate(contents):
  print("[%d%d]: %s" %(i, len(contents), con))

[010]: Regression
[110]: Classification
[210]: SYM
[310]: Clustering
[410]: Dimension reduction
[510]: NN
[610]: CNN
[710]: AE
[810]: GAN
[910]: RNN


### 함수

In [ ]:
def sum(a, b):
  return a+b

x = 10.0
y = 20.0
print("%.1f + %.1f = %1f" %(x, y, sum(x, y)))

10.0 + 20.0 = 30.000000


### 리스트

In [ ]:
a = []
b = [1, 2, 3]
c = ["Hello", ",", "world"]
d = [1, 2, 3, "x", "y", "z"]
x = []
print(x)

x.append('a')
print(x)

x.append(123)
print(x)

x.append(["a", "b"])
print(x)

[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


### 딕셔너리

In [ ]:
dic = dict()
dic["name"] = "Heekyung"
dic["town"] = "Goyang city"
dic["job"] = "Assistant professor"
print(dic)

{'name': 'Heekyung', 'town': 'Goyang city', 'job': 'Assistant professor'}


### 클래스

In [ ]:
class Student:
  # 생성자
  def __init__(self, name):
    self.name = name

  # 메써드
  def study(self, hard = False):
    if hard:
      print("%s 학생은 열심히 공부합니다." %self.name)

    else:
      print("%s 학생은 공부합니다." %self.name)

s = Student('Heekyung')
s.study()
s.study(hard = True)

Heekyung 학생은 공부합니다.
Heekyung 학생은 열심히 공부합니다.


---
# 2. 벡터, 행렬 연산, 그래프 그리기
---

### 라이브러리(패키지) 로드

In [1]:
import numpy as np

### 프린트

In [3]:
def print_val(x):
  print("Type:", type(x))
  print("Shape:", x.shape)
  print("값:\n", x)
  print(" ")

rank 1 np array

In [4]:
x = np.array([1, 2, 3])
print_val(x)

x[0] = 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]
 


### rank 2 np array

In [5]:
y = np.array([[1, 2, 3], [4, 5, 6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 


### rank 2 ones

In [6]:
a = np.ones((3, 2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


### rank 2 zeros

In [7]:
a = np.zeros((2, 2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 


### rank 2 단위행렬(identity matrix)

In [8]:
a = np.eye(3, 3)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


### 랜덤 행렬(uniform: 0~1 사이 모든 값들이 나올 확률이 같음

In [12]:
a = np.random.random((4, 4))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[0.0073261  0.59159101 0.22401037 0.83588287]
 [0.18419592 0.01015723 0.16456133 0.78971967]
 [0.66943763 0.07601246 0.43702973 0.3959692 ]
 [0.89577497 0.23814309 0.9305828  0.02534838]]
 


### 랜덤 행렬(Gaussian: 0을 평균으로 하는 가우시안 분포를 따르는 랜덤값

In [14]:
a = np.random.randn(4, 4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[-0.45212436 -0.81626552 -0.30261901  1.53412396]
 [ 0.30711366 -0.90799152  0.0558517  -0.74310039]
 [ 1.8396854  -0.87198968 -0.06069062  1.46806228]
 [-3.54172413 -0.39877009 -1.40870595 -2.08499201]]
 
